### PR TITLE
Add badge for master build on Quay.

### PR DESCRIPTION
**Pull request by sbose78**
podman pull quay.io/redhat-developer/openshift-jenkins-operator

### CODE REVIEW

**Comment by sbose78** [comment]
image

This is how it looks.

That text in general is irrelevant. I've copy pasted the snippet from Quay as is :)

**Comment by DhritiShikhar** [comment]
@akram +1 for `container`

**Comment by sbose78** [comment]
Folks, it's a code snippet that is being used as is from Quay. Let's not change it at all.

**Comment by waveywaves** [comment]
Looks good  :) /lgtm

**Pull request merged**
