### PR TITLE
Replace "placeholder" text displayed in UI

### PR DESCRIPTION
**Pull request by ldimaggi**
This text is also corrected in this pull request:
Screenshot from 2019-09-26 13-29-04

### CODE REVIEW

**Comment by akram** [comment]
@ldimaggi A PR moving to 0.0.2 made this PR to required rebase. We will need to `git pull upstream master --rebase`
And your changes will be conflicting, you then need to transfer them to the new csv (v0.0.2) file and recommit again.

**Comment by ldimaggi** [comment]
Rebased successfully - can you look at this again and merge it? Thx!

**Pull request merged**
